# Generated by Django 3.1.6 on 2021-02-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
