# Generated by Django 3.1.6 on 2021-02-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.AddField(
            model_name='state',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
