# Generated by Django 3.1.6 on 2021-02-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0003_auto_20210216_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='nameCourse',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='institution',
            name='nameInstitution',
            field=models.CharField(max_length=30),
        ),
    ]
